# Typos configuration (lightweight)
[default]
extend-ignore-re = [
  "http://[\\\\w\\\\./\\\\-]+",
  "https://[\\\\w\\\\./\\\\-]+",
]

[default.extend-words]
wrk = "wrk"  # HTTP benchmarking tool

[files]
extend-exclude = [
  "target/**",
  "**/*.svg",
  "**/*.png",
]
