[package]
name = "rust-miniss"
version = "0.1.0"
edition = "2021"
authors = ["Your Name"]
description = "A Rust implementation of miniss - a toy Seastar-like async runtime"
license = "MIT OR Apache-2.0"

[dependencies]
# Core async primitives
futures = "0.3"
pin-project-lite = "0.2"

# Concurrency utilities
crossbeam = "0.8"
crossbeam-queue = "0.3"
once_cell = "1.19"
crossbeam-channel = "0.5"

# System programming
nix = { version = "0.27", features = ["signal", "time", "sched"] }
libc = "0.2"

# IO backends (Linux only)

# Utilities
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
num_cpus = "1.16"
rand = "0.8"

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = "0.6"

[dev-dependencies]
criterion = "0.5"
proptest = "1.4"
tokio = { version = "1", features = ["full"] }

# Target platform: Linux only
# Use OrbStack or Docker for development on macOS

[[example]]
name = "hello_world"

[[example]]
name = "multicore_demo"

[profile.release]
lto = true
codegen-units = 1
