version: '3.8'

services:
  rust-miniss:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rust-miniss-dev
    volumes:
      - .:/workspace
      - cargo-cache:/root/.cargo/registry
      - target-cache:/workspace/target
    working_dir: /workspace
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    # 特权模式用于性能测试和CPU亲和性设置
    privileged: true
    # 分配更多资源用于测试
    cpus: '4.0'
    mem_limit: 4g
    stdin_open: true
    tty: true
    command: bash

volumes:
  cargo-cache:
  target-cache:
