[profile.default]
# Run tests in parallel; nextest defaults to num_cpus threads, can override here.
retries = 1
failure-output = "immediate"
status-level = "all"

[profile.ci]
retries = 0
failure-output = "immediate"
status-level = "all"

[profile.nightly]
retries = 0
failure-output = "immediate"
status-level = "all"

[store]
# Store test results artifacts
dir = "target/nextest"
