name: Benchmarks and Profiling

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - feat/**
      - feat/http-mvp
  schedule:
    - cron: '0 6 * * *'

permissions:
  contents: write

jobs:
  bench:
    name: Run Criterion Benchmarks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CARGO_TERM_COLOR: always
      RUSTFLAGS: -C debuginfo=1
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y liburing-dev build-essential

      - name: Run Criterion benches (HTML reports)
        shell: bash
        run: |
          set -euxo pipefail
          # Run benchmarks with io-uring feature
          cargo bench --features io-uring

      # Flamegraphs removed - requires privileged mode not available on GitHub Actions

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: criterion-reports
          path: target/criterion

      - name: Publish Criterion reports to gh-pages
        if: ${{ github.event_name != 'pull_request' }}
        shell: bash
        run: |
          set -euxo pipefail
          OUT_DIR=gh-pages-out
          rm -rf "$OUT_DIR"
          mkdir -p "$OUT_DIR/criterion"
          cp -r target/criterion/* "$OUT_DIR/criterion/" || true
          # Add a simple index
          cat > "$OUT_DIR/index.html" <<'HTML'
          <html><head><title>rust-miniss Benchmarks</title></head>
          <body>
            <h1>rust-miniss Benchmarks</h1>
            <ul>
              <li><a href="criterion/index.html">Criterion Report</a> (open individual benchmarks inside)</li>
            </ul>
          </body></html>
          HTML

          # Publish to gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git fetch --no-tags origin gh-pages || true
          git checkout -B gh-pages
          rm -rf ./*
          cp -r "$OUT_DIR"/* .
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to publish"
          else
            git commit -m "Update Criterion reports and flamegraphs [skip ci]"
            git push origin gh-pages --force
          fi
