name: Codespell

on:
  push:
    branches:
      - main
      - feat/**
      - feat/http-mvp
      - develop
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run codespell
        uses: codespell-project/actions-codespell@v2
        with:
            config: .codespellrc
            path: .
