name: Typos

on:
  push:
    branches:
      - main
      - feat/**
      - feat/http-mvp
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run typos
        uses: crate-ci/typos@v1.35.3
        with:
          config: .typos.toml
          files: .

